# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irwoPKDbTmxlwsvM_sMwUBnsyFcLZ2BQ

## Recomendación aleatoria

1. Generar la tabla de actividades
"""

import numpy as np
import sys


print(sys.argv[1])
